/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2018-10-01 07:14:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/home/shreyansh/eclipse/jee-photon/eclipse/DBMS/shreyansh_final/target/repo/org/springframework/spring-webmvc/4.2.1.RELEASE/spring-webmvc-4.2.1.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1441053344000L));
    _jspx_dependants.put("jar:file:/home/shreyansh/eclipse/jee-photon/eclipse/DBMS/shreyansh_final/target/repo/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("file:/home/shreyansh/eclipse/jee-photon/eclipse/DBMS/shreyansh_final/target/repo/javax/servlet/jstl/1.2/jstl-1.2.jar", Long.valueOf(1538377936000L));
    _jspx_dependants.put("file:/home/shreyansh/eclipse/jee-photon/eclipse/DBMS/shreyansh_final/target/repo/org/springframework/spring-webmvc/4.2.1.RELEASE/spring-webmvc-4.2.1.RELEASE.jar", Long.valueOf(1538377936000L));
    _jspx_dependants.put("jar:file:/home/shreyansh/eclipse/jee-photon/eclipse/DBMS/shreyansh_final/target/repo/org/springframework/spring-webmvc/4.2.1.RELEASE/spring-webmvc-4.2.1.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1441053344000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("    <style>\n");
      out.write("       /* Set the size of the div element that contains the map */\n");
      out.write("      #map {\n");
      out.write("        height: 400px;  /* The height is 400 pixels */\n");
      out.write("        width: 100%;  /* The width is the width of the web page */\n");
      out.write("       }\n");
      out.write("       #main-footer {\n");
      out.write("    background: #fff;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#main-footer p a {\n");
      out.write("    padding-bottom: 40px;\n");
      out.write("    font-size: 25px;\n");
      out.write("    text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("#main-footer p {\n");
      out.write("    text-align: center; \n");
      out.write("}\n");
      out.write("\n");
      out.write(".social-links {\n");
      out.write("    list-style:none;\n");
      out.write("    margin:0;\n");
      out.write("    padding:0;\n");
      out.write("    margin-bottom:30px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".social-links li{\n");
      out.write("    display:inline-block;\n");
      out.write("    margin:0 5px;\n");
      out.write("    border-radius:3px;\n");
      out.write("    box-shadow:0 4px 0 transparent;\n");
      out.write("    -webkit-transition:all .3s ease-out;\n");
      out.write("    transition:all .3s ease-out;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".social-links li a {\n");
      out.write("    display:block;\n");
      out.write("    color:#fff;\n");
      out.write("    font-size:21px;\n");
      out.write("    width:50px;\n");
      out.write("    height:50px;\n");
      out.write("    line-height:50px;\n");
      out.write("    text-align:center;\n");
      out.write("    background:#509B9E;\n");
      out.write("    border-radius:50%;\n");
      out.write("    -webkit-transition:all .3s ease-out;\n");
      out.write("    transition:all .3s ease-out;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".social-links li a:hover {\n");
      out.write("    color:#fff;\n");
      out.write("    background:#f9398c;\n");
      out.write("}\n");
      out.write("    </style>\n");
      out.write("    \n");
      out.write("        <title>Somnath Sevashram</title>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("        <link href=\"https://fonts.googleapis.com/css?family=Montserrat:300,400,600&amp;subset=latin-ext\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("        <!-- CSS -->\n");
      out.write("        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("        <link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("        <!-- JS -->\n");
      out.write("        <script src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"></script>\n");
      out.write("        <script src=\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\"></script>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div class=\"site\" id=\"page\">\n");
      out.write("            <a class=\"skip-link sr-only\" href=\"#main\">Skip to content</a>\n");
      out.write("\n");
      out.write("            <!-- Options headline effects: .rotate | .slide | .zoom | .push | .clip -->\n");
      out.write("            <section class=\"hero-section hero-section--image clearfix clip\">\n");
      out.write("                <div class=\"hero-section__wrap\">\n");
      out.write("                    <div class=\"hero-section__option\">\n");
      out.write("                        <img src=\"");
      if (_jspx_meth_c_005furl_005f3(_jspx_page_context))
        return;
      out.write("\" alt=\"bg\">\n");
      out.write("                    </div>\n");
      out.write("                    <!-- .hero-section__option -->\n");
      out.write("\n");
      out.write("                    <div class=\"container\">\n");
      out.write("                        <div class=\"row\">\n");
      out.write("                            <div class=\"offset-lg-2 col-lg-8\">\n");
      out.write("                                <div class=\"title-01 title-01--11 text-center\">\n");
      out.write("                                    <h2 class=\"title__heading\">\n");
      out.write("                                        <span>Somnath Sevashram</span>\n");
      out.write("                                        <!-- <strong class=\"hero-section__words\">\n");
      out.write("                                            <span class=\"title__effect is-visible\">AweSome</span>\n");
      out.write("                                            <span class=\"title__effect\">Creative</span>\n");
      out.write("                                            <span class=\"title__effect\">Free</span>\n");
      out.write("                                        </strong> -->\n");
      out.write("                                    </h2>\n");
      out.write("                                    <!-- <div class=\"title__description\">Delivering extraordinary creations from the very beginning of the time!</div> -->\n");
      out.write("\n");
      out.write("                                    <!-- Options btn color: .btn-success | .btn-info | .btn-warning | .btn-danger | .btn-primary -->\n");
      out.write("                                    <div class=\"title__action\"><a href=\"login\" class=\"btn btn-success\">Client Login</a></div>\n");
      out.write("                                    </br> <div class=\"title__action\"><a href=\"login\" class=\"btn btn-success\">Employee Login</a></div>\n");
      out.write("                                    </br><div class=\"title__action\"><a href=\"register\" class=\"btn btn-success\">Client Signup</a></div>\n");
      out.write("                                    </br><div class=\"title__action\"><a href=\"registerSupplier\" class=\"btn btn-success\">Supplier Registration</a></div>\n");
      out.write("                                </div> <!-- .title-01 -->\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </section>\n");
      out.write("            <div id=\"map\"></div>\n");
      out.write("    <script>\n");
      out.write("// Initialize and add the map\n");
      out.write("function initMap() {\n");
      out.write("  // The location of Uluru\n");
      out.write("  var smnthsvrm = {lat: 22.8083697, lng: 86.2026957};\n");
      out.write("  // The map, centered at Uluru\n");
      out.write("  var map = new google.maps.Map(\n");
      out.write("      document.getElementById('map'), {zoom: 10, center: smnthsvrm});\n");
      out.write("  // The marker, positioned at Uluru\n");
      out.write("  var marker = new google.maps.Marker({position: smnthsvrm, map: map});\n");
      out.write("}\n");
      out.write("    </script>\n");
      out.write("    <!--Load the API from the specified URL\n");
      out.write("    * The async attribute allows the browser to render the page while the API loads\n");
      out.write("    * The key parameter will contain your own API key (which is not needed for this tutorial)\n");
      out.write("    * The callback parameter executes the initMap() function\n");
      out.write("    -->\n");
      out.write("    <script async defer\n");
      out.write("    src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyDoGBVFVxUt8rge808tC5ztfqEs94ig-ZQ&callback=initMap\">\n");
      out.write("    </script>\n");
      out.write("        </div>\n");
      out.write("\t\t\n");
      out.write("        <!-- <div class=\"button-group\">\n");
      out.write("        \t<a href=\"index-color.html\" class=\"btn btn-outline-success button-sm\">Color</a>\n");
      out.write("            <a href=\"index-slider.html\" class=\"btn btn-outline-success button-sm\">Slider</a>\n");
      out.write("            <a href=\"index-video.html\" class=\"btn btn-outline-success button-sm\">Video Background</a>\n");
      out.write("        </div> -->\n");
      out.write("\n");
      out.write("\t<footer id=\"main-footer\" class=\"add-padding border-top-color2\">\n");
      out.write("\t\t\n");
      out.write("\t\t\t<div class=\"container\">\n");
      out.write("\n");
      out.write("\t\t\t\t<p>Contact Us</p><br>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<ul class=\"social-links text-center\">\n");
      out.write("\t\t\t\t\t<li><a href=\"tel:9654070844\" target=\"_blank\"><i class=\"fa fa-phone\"></i></a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t<p class=\"text-center\">&copy; 2018 - Somnath Sevashram</p>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</footer>\n");
      out.write("        <!-- JS -->\n");
      out.write("        <script src=\"assets/js/plugins/animate-headline.js\"></script>\n");
      out.write("        <script src=\"assets/js/main.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(72,20) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/resources/home/css/main.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent(null);
      // /WEB-INF/views/home.jsp(75,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("/resources/home/js/vendor/modernizr-2.8.3.min.js");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f2_reused = false;
    try {
      _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f2.setParent(null);
      // /WEB-INF/views/home.jsp(76,21) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f2.setValue("/resources/home/js/vendor/jquery-1.12.0.min.js");
      int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
      if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      _jspx_th_c_005furl_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f2, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f3 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f3_reused = false;
    try {
      _jspx_th_c_005furl_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f3.setParent(null);
      // /WEB-INF/views/home.jsp(86,34) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f3.setValue("/resources/home/images/index.jpg");
      int _jspx_eval_c_005furl_005f3 = _jspx_th_c_005furl_005f3.doStartTag();
      if (_jspx_th_c_005furl_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f3);
      _jspx_th_c_005furl_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f3, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f3_reused);
    }
    return false;
  }
}
